---
- hosts: webservers
  become: yes
  tasks:
    - name: Install apache2
      apt: 
        name: apache2
        update_cache: yes
        state: present
    - name: Ensure Apache2 Is Installed And Started On Boot
      service:
        name: apache2
        state: started
        enabled: yes