pipeline {
  agent { label 'slave' }
  stages {
    stage('npm install') {
      when {
        expression {
          params.REQUESTED_ACTION == 'Build'
        }

      }
      steps {
        sh 'npm install'
      }
    }
    stage('npm run build') {
      when {
        expression {
          params.REQUESTED_ACTION == 'Build'
        }

      }
      steps {
        sh 'cd /Ansible_Jenkins_PIpeline-master/Jenkins/npm_demo/'
        sh 'npm run build'
      }
    }
  }
  parameters {
    choice(name: 'REQUESTED_ACTION', choices: '''Build
''', description: 'Type of action to perform')
  }
}
