pipeline {
  agent any
  stages {
    stage('npm install') {
      when {
        expression {
          params.REQUESTED_ACTION == 'Build'
        }

      }
      steps {
        sh 'npm install'
      }
    }
  stage('npm install') {
    when {
      expression {
        params.REQUESTED_ACTION == 'Build'
      }

    }
    steps {
      sh 'npm install'
    }
  }
  parameters {
    choice(name: 'REQUESTED_ACTION', choices: '''Build
''', description: 'Type of action to perform')
  }
}
